### ISSUE TITLE
GUI does not show entire button for "Extract story elements" in Elements widget

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#40]
##### Story Navigator version
0.0.18 (commit https://github.com/navigating-stories/orange-story-navigator/commit/8732988e67920716c2eef3eef0af7d6e936da74f)

##### Orange version
3.36.2, Ubuntu 20.04

##### Expected behavior
See entire text.

##### Actual behavior
Can only see parts of the text.

##### Steps to reproduce the behavior
any workflow with `Elements` widget

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/34867bfd-2481-459f-88ae-de83623bc892)

**Comment by kodymoodley** [comment]
I think the best solution is to have a flexible length for the button. Need to research but this might be useful: https://forum.qt.io/topic/121326/how-to-size-qpushbuttons-to-width-of-text-and-pack-left?_=1711523912775

**Comment by ThijsVroegh** [comment]
This is probably specific to ubuntu, since this is no issue for Mac m1 and windows 11

**Comment by eriktks** [comment]
Yes, I also experienced this problem on Ubuntu Linux. The problem can be solved by removing the width and height definitions of the button, see PR #72
