### ISSUE TITLE
make useful defaults for links?

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#42]
When creating an `Actors` widget:
- when I first link from `Import Documents`, I get suggested to link "Corpus -> Stories", which is correct. (see screenshot case 1)
- when I first link from a data table widget, I get suggested to link "Story elements -> Stories", which is incorrect. (case 2)
-  (A similar issue appears when the `Elements` widget is first linked to a table widget, and then the table widget is linked to an `Actors` widget (case 3)

It would be nice if to have the right defaults also for the second and third case.

case 1:
![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/c68c77f6-1738-4c64-a2b8-646a3eb52d40)

case 2:
![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/0df7d4b3-da24-4093-b6eb-8a55799c2718)

case 3:
![image](https://github.com/navigating-stories/orange-story-navigator/assets/55716026/c7be85d2-fd27-4500-9413-188f160670d8)

**Comment by kodymoodley** [comment]
This can be solved definitely. It seems possible to disable inputs / outputs based on incompatibility of types or some condition. See the screenshot below. But I don't know where exactly in the source code to find this functionality. Needs some investigation. 
[
<img width="675" alt="disable_inputs_outputs_orange" src="https://github.com/navigating-stories/orange-story-navigator/assets/13569029/f512f5b5-a7b8-4dc8-9e4a-bd77eafb5908">
](url)

**Comment by kodymoodley** [comment]
Code could be in Orange itself (not necessarily only in Network add-on). Could also be in other Orange add-ons / widgets.

**Comment by f-hafner** [comment]
I have looked around and tried some things, but have not worked it out. 
- I noticed a similar behavior as what Kody described on the `Table` widget -- so it seems like a common underlying behavior across widgets which we for some reason have not managed to achieve.
- I looked through the source code for both the `Table` widget and the `Network Explorer` widgets, but don't see how they get to this behavior.
- I did extensive online search but found nothing
- I looked at the [developer documentation](https://orange3.readthedocs.io/projects/orange-development/en/latest/tutorial-channels.html) for widgets, but found nothing
- I  asked in the Orange discord channel, waiting for responses.

**Comment by f-hafner** [comment]
it seems the behavior in the screenshot above for the network explorer widget stems from Orange's built-in type checking. It turns out that `Corpus` -- the `Stories` input for the Actor Analysis and Action Analysis widgets -- is a subclass of `Table`: https://github.com/biolab/orange3-text/blob/f73d42fef394f91f5810373ec38a13e1d015e41b/orangecontrib/text/corpus.py#L47

Thus, the `Table` output from the tagger is consistent with the `Corpus` type for the `Stories` input. 

We discussed two options:
- raise warning when undesired inputs and outputs are connected 
- return the whole text also from the tagger, but this would require rewriting much of the code for Actor and Action analysis.
