### ISSUE TITLE
text of the stories changes when running the analysis 

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#43]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2 
orange-network version: 1.9.0
orange-text version: 1.15.0

##### Actual behavior
When I open the actors widget, the story I am using is displayed complete. As soon as I check the boxes for highlighting the subjects, other potential actors etc. parts of my story disappear. 

##### Expected behavior
I expect the text to be displayed complete

##### Steps to reproduce the behavior
1. import file 
2. select elements widget 
3. connect file with ‘elements’ 
4. connect ‘elements’ with data table 
5. select actors widget  
6. connect elements to actors 
7. connect story to actors 
8. open actors widget --> story is complete 
9. have subjects highlighted --> parts of the text disappear  
10. 
##### Additional info (worksheets, data, screenshots, ...)

General screenshots

<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/6c71f8b6-a683-4186-bdd2-a77e216e708c">

<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/591569e4-d536-4c77-8ec7-9a53ccd60d64">

-  I used a txt file, the story is called ‘over leven’ 
-  Workflow file: screenshot of my workflow 
<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/c4900576-1236-4fd9-841c-36edcf237a1e">

- I have tried with the Moataz Rageb – story and the same happens. If I unclick the sentence subject box, then the text remains incomplete. The same happened with the story ‘eenzaamheid’, which I used before and I can’t remember having this issue. I have tried with ‘sperziebonen’, encountered the same problem, but then I saw that the first paragraph, which was missing after clicking the subject box, was moved to the end of the text.

**Comment by kodymoodley** [comment]
Need more info about which sentences are missing / removed and in which stories / data.

**Comment by kodymoodley** [comment]
Saartje will send sentences for "eenzaamheid" / "jalouzie".

**Comment by f-hafner** [comment]
@kodymoodley , I have trouble reproducing this. I tried with the "eenzamheid" and the "overleven" stories. I copy-pasted the displayed text from the Actors widget into a text file and ran a `diff` between them. 
For "eenzamheid", I find 0 difference.
 For "overleven", it's hard to see full words/sentences missing. There are sometimes additional letters at the start of a line or additional white spaces around commas.

**Comment by kodymoodley** [comment]
fixed by #58
