### ISSUE TITLE
when rerunning the analysis with the elements widget, the story appears a second time when opening the action or actors widget. When I want to select that story, I get an error. 

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#44]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2  
Orange-text version: 1.15.0  
Orange-network version: 1.9.0 

##### Expected behavior
I would not expect the story to appear a second time, but it seems as if rerunning the element widget causes the story to appear a second time. If it is necessary that the story appears twice, than there shouldn’t be an error.

##### Actual behavior
When I import a file, do some analyses, go back to elements to choose how many segments I want in my story, click on ‘extract elements’ and go back to the (i.c.) action widget, my story is displayed twice. If I click on the second story, I get an error.

##### Steps to reproduce the behavior
1. Import file 
2. select elements, connect file to elements, retract story elements 
3. select action widget 
4. connect story and elements to action widget 
5. open action widget and click/unclick the tense boxes 
6. go back to elements 
7. choose number of segments 
8. retract story elements 
9. reopen action widget --> the story is displayed twice on the left. When selecting the story, an error appears 

##### Additional info (worksheets, data, screenshots, ...)
Important: the problem I described under #43  happened here as well: after clicking/unclicking the tense boxes, the text changes. 

<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/cc24a5b8-9344-4965-a269-97f083afe54c">

**Comment by kodymoodley** [comment]
This is a genuine bug and I was able to reproduce it.

**Comment by kodymoodley** [comment]
related to https://github.com/navigating-stories/orange-story-navigator/issues/51

**Comment by eriktks** [comment]
See PR #71
