### ISSUE TITLE
 when using my own dictionary, a lot of words which are not in the dictionary are highlighted as well 

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#46]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2
Orange-text version: 1.15.0 
Orange-network version: 1.9.0 

##### Expected behavior
 I expect that only the words that are in my dictionary are highlighted when selecting custom tags

##### Actual behavior
when using my own dictionary, a lot of words which are not in the dictionary are highlighted as well

##### Additional info (worksheets, data, screenshots, ...)
<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/13542f57-d3f1-4df0-bb41-4db26431561b">

**Comment by kodymoodley** [comment]
Which words are expected / unexpected?

**Comment by kodymoodley** [comment]
Saartje will send dictionary to reproduce

**Comment by kodymoodley** [comment]
Similar to https://github.com/navigating-stories/orange-story-navigator/issues/48?

**Comment by kodymoodley** [comment]
Turns out it was due to categorical data type in dictionary column (need to update column data type to TEXT always).
