### ISSUE TITLE
unexpected error when opening the actors widget 

### ISSUE THREAD

**Issue by f-hafner** [navigating-stories/orange-story-navigator#47]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2
Orange-text version: 1.15.0 
Orange-network version: 1.9.0 

##### Expected behavior
I think the error occurs because after choosing the elements widget I forgot to extract the elements --> can the tool give a reminder like “extract the elements” instead of giving an error? 

##### Actual behavior
I imported a story and wanted to run an analysis but when opening the actors widget an ‘unexpected error’ occured

##### Steps to reproduce the behavior

1. import file 
2. select elements widget 
3. connect file with ‘elements’ 
4. import dictionary 
5. connect dictionary to elements  
6. select actors widget 
7. connect elements to actors (line stays red) 
8. connect document to actors --> error 

##### Additional info (worksheets, data, screenshots, ...)

I noticed that you first have to connect your file to the widget and only then the elements. If you do this in the reverse order than you will get an error

<img width="800" alt="image" src="https://github.com/navigating-stories/orange-story-navigator/assets/55716026/0edbcaa7-cccf-4f12-806e-1b8558465b36">

**Comment by kodymoodley** [comment]
I think this is not a bug. The elements need to be **computed** first before connecting to Actor widget.

**Comment by kodymoodley** [comment]
Need to click on "Extract story elements" button

**Comment by kodymoodley** [comment]
Resolved. Not a bug. Incorrect usage of elements widget related to problem in https://github.com/navigating-stories/orange-story-navigator/issues/42
