### ISSUE TITLE
the tool does not display my custom tags

### ISSUE THREAD

**Issue by ThijsVroegh** [navigating-stories/orange-story-navigator#48]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2

##### Expected behavior
I expect the text not to change and I expect the words of my dictionary to be highlighted in green

##### Actual behavior
Same problem as described in number 4 but now I used another dictionary (the dictionary you created, Kody) + same problem as in number 1: text changes

##### Steps to reproduce the behavior
1. import file
2. select elements widget
3. connect file with ‘elements’
4. import dictionary
5. connect dictionary to elements 
6. select 10 segments in story
7. extract elements
6. select actors widget
8. connect elements to actors 
8. connect document to actors 
9. open actors widget
10. Click on sentence subjects --> order of the sentences of the text changes
11. Click on custom tags --> custom tags are displayed in strange way  

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/21f430f5-6ea0-49df-b45e-d1dd4fb5fbb0)

**Comment by kodymoodley** [comment]
Need the dictionary to reproduce. Which custom tags should be displayed?

**Comment by ThijsVroegh** [comment]
see #46 solution
