### ISSUE TITLE
After saving a workflow, I opened it again but some results had disappeared.

### ISSUE THREAD

**Issue by ThijsVroegh** [navigating-stories/orange-story-navigator#49]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2

##### Expected behavior
I expect the tables and graphs not to change or disappear after I saved them

##### Actual behavior
after saving a workflow, I opened it again but some results had disappeared.

##### Steps to reproduce the behavior
1.  I created this workflow in which the data table and the bar plots displayed results
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/1f45f4d0-50b7-4dfe-885b-639fc25f831e)
2. I saved it as ‘workflow jaloezie’
3. I opened it again but the bar plots and data table don’t show any results anymore:
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/e1f9e323-6861-4c2c-a152-ce04cbae0bbe)

**Comment by kodymoodley** [comment]
Probably not a bug... I will check with the filer and update the issue.

**Comment by kodymoodley** [comment]
Problem with usage. Need to make sure you connect "Data" and not "Selected Data" for inputs / outputs.
