### ISSUE TITLE
I can’t save results

### ISSUE THREAD

**Issue by ThijsVroegh** [navigating-stories/orange-story-navigator#50]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2

##### Actual behavior
I try to save a barplot but get the message ‘empty input, nothing has saved’

##### Steps to reproduce the behavior
1.	I created a workflow
2.	I created a barplot of the subjects
3.	I connect the barplot to ‘save as’
4.	I save the result on my pc but get the message ‘empty input, nothing has saved’. I tried to save it as a tab file and as an excel file but got the same message

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/1d55449a-938f-4c08-93e4-3d2f8eba831c)

**Comment by kodymoodley** [comment]
I suspect this is not a bug at all. I think "Selected data" is used as input for the save widget and it should be "Data".
