### ISSUE TITLE
The documentviewer shows texts and titles wrong

### ISSUE THREAD

**Issue by ThijsVroegh** [navigating-stories/orange-story-navigator#51]
##### Story Navigator version
0.0.18

##### Orange version
3.36.2 

##### Expected behavior
I expect the texts in the data set to be displayed in the correct order and I expect titles and text to match.

##### Actual behavior
I created a dataset to test the different functions but the viewer shows texts that are not even in the dataset

##### Steps to reproduce the behavior
1.	I created a dataset of 17 texts
2.	I imported the dataset 
3.	Connect elements, extract elements
4.	Connect actors widget to both document and elements
5.	If I open the actors widget and go through the texts, I see that the titles do not match the displayed text. Only the first two texts are correctly displayed, all the rest got mixed up.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/7f054ec3-7001-4419-85fa-adc3849299bb)

![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/cef5c0ee-579d-4f15-a348-c76c0ccdf67b)

![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/0065c0dc-fdd2-43b7-947c-d35343ab27e0)

![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/76d88036-43d7-4111-a978-b0f895497c6c)

![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/7ce6fde2-213b-424d-b81b-eead63421607)

**Comment by kodymoodley** [comment]
We need the input stories / data to reproduce this. I will attach it here when I find it.

**Comment by kodymoodley** [comment]
Issue with dictionary (story_title, story_id) key - value assignment perhaps?

**Comment by kodymoodley** [comment]
Fixed in #58.
