### ISSUE TITLE
Order of the text in the Actors widget is different from the original order

### ISSUE THREAD

**Issue by ThijsVroegh** [navigating-stories/orange-story-navigator#54]
##### Story Navigator version
0018

##### Orange version
3.36.2

##### Expected behavior
The order of the output in the Actors widget, togehter with the colors, would be identical to the original text

##### Actual behavior
The text in the actors widget is now mixed up, and no longer following the same order as the original

##### Steps to reproduce the behavior
Connect Actors widget with Elements and Import Documents widgets
Select story elements to highlight
See output in the right screen  

##### Additional info (worksheets, data, screenshots, ...)
![image](https://github.com/navigating-stories/orange-story-navigator/assets/56916115/a379500e-a7ef-414d-9b9b-bb9ca2f29fdd)

**Comment by kodymoodley** [comment]
Fixed by #58

**Comment by ThijsVroegh** [comment]
Story title: NL de nieuwe wereld 1.6.txt.

"Er wonen ongeveer 40 mensen , jong en oud" is This sentence is halfway in the actors output, although in the original text it is the 3rd sentence. Somehow, the first 1 or 2 sentences are correct, but afterwards the sentences get mixed up
