### ISSUE TITLE
Citation, doi, and archiving

### ISSUE THREAD

**Issue by stefsmeets** [navigating-stories/orange-story-navigator#66]
As far as I can tell, the software does not have a doi yet. We should set up the connection with Zenodo and add a citation.cff file.

- [x] Automatic upload to Zenodo
- [x] Add citation.cff -> 81c466d4ec4e4d834f0e9c5e06a4b2b5e5044227
- [ ] Update badges in readme

**Comment by kodymoodley** [comment]
Hi @stefsmeets , it does have a DOI and is archived on Zenodo since April 2024 - see here: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.10994947.svg)](https://doi.org/10.5281/zenodo.10994947)

We don't have a citation.cff yet though, I will work on one. I will add the DOI badge to the readme

**Comment by ThijsVroegh** [comment]
@kodymoodley : I already made a start with the citation.cff as part of the howtocite in the documentation; see the 'howtocite.md' at the bottom. Perhaps that is of use?

**Comment by kodymoodley** [comment]
> @kodymoodley : I already made a start with the citation.cff as part of the howtocite in the documentation; see the 'howtocite.md' at the bottom. Perhaps that is of use?

Thanks @ThijsVroegh, also a good idea to include a CITATION.cff file in the root of the repo. See [here](https://github.com/NLeSC/python-template/blob/main/CITATION.cff) for example:

**Comment by ThijsVroegh** [comment]
Ok, thanks!

**Comment by stefsmeets** [comment]
Seems like the citation.cff was added in 81c466d4ec4e4d834f0e9c5e06a4b2b5e5044227

**Comment by stefsmeets** [comment]
And the badges are also added, this issue can be closed! 🚀
