### ISSUE TITLE
Orange add-on menu screenshot not displaying under Installation section of documentation

### ISSUE THREAD

**Issue by kodymoodley** [navigating-stories/orange-story-navigator#74]
##### Expected behavior
Screenshot is visible on [this page](https://orange-story-navigator.readthedocs.io/en/latest/widgets/installation.html) showing where to find the add-on installation menu.

##### Actual behavior
Screenshot is not visible.

![image](https://github.com/navigating-stories/orange-story-navigator/assets/13569029/8b7e0278-9116-4b0b-8149-15e260cb3589)

##### Steps to reproduce the behavior
Go [here](https://orange-story-navigator.readthedocs.io/en/latest/widgets/installation.html) and check if there is a screenshot displayed under section "Open Add-on manager"

**Comment by eriktks** [comment]
solved by PR #79
