### ISSUE TITLE
Citation texts are not displayed in copy-paste green boxes on rtd documentation page

### ISSUE THREAD

**Issue by kodymoodley** [navigating-stories/orange-story-navigator#75]
##### Expected behavior

Citation text [here](https://orange-story-navigator.readthedocs.io/en/latest/widgets/howtocite.html) should be displayed in green code blocks to make it easier to copy-paste, and to be generally more visible or distinct from the rest of the text.

In other words, the text should be formatted more like this:

![image](https://github.com/navigating-stories/orange-story-navigator/assets/13569029/b8524a05-b4d0-4a9e-ad5a-3099aa86574c)

##### Actual behavior

The citation text is formatted just like the rest of the text making it more difficult to copy-paste / to quickly find in the text without having to read everything.

![image](https://github.com/navigating-stories/orange-story-navigator/assets/13569029/e7f31a1b-a3cc-4cf6-81c7-0eea8c2131ae)

**Comment by eriktks** [comment]
solved by PR #79

**Comment by eriktks** [comment]
solved by PR #79
