### ISSUE TITLE
Custom tags dictionary words are not correctly highlighted in Actors and Actions widgets

### ISSUE THREAD

**Issue by kodymoodley** [navigating-stories/orange-story-navigator#77]
##### Story Navigator version

0.0.19

##### Orange version

3.37.0

##### Expected behavior
Correct words are highlighted in green when "Custom tokens" checkbox is checked in the Actors and Actions widgets. That is, only the words contained in the custom dictionary I supply should be highlighted and not any other words.

##### Actual behavior
Many other words in the story texts are highlighted in green that are not in the Custom tags dictionary file. See screenshot below:

![image](https://github.com/navigating-stories/orange-story-navigator/assets/13569029/e9c82672-ca26-4dbb-87ae-647f2d6965eb)

##### Steps to reproduce the behavior
Create the workflow as depicted in next section. Import the stories attached and import the custom dictionary file attached. Open the Actors / Actions widgets and ensure the checkbox for "Custom tokens" is selected.

##### Additional info (worksheets, data, screenshots, ...)

Workflow I used:

![image](https://github.com/navigating-stories/orange-story-navigator/assets/13569029/0ceefac6-7ce9-4348-9bbf-24a191fe7d01)

Stories I loaded:
[corona_testdata.zip](https://github.com/user-attachments/files/16085373/corona_testdata.zip)

Custom dictionary file I used:
[dict_single_column.csv](https://github.com/user-attachments/files/16085375/dict_single_column.csv)

**Comment by kodymoodley** [comment]
Similar to #46 and #48 but the solution proposed in #46 does not apply here (I have tried it).

**Comment by kodymoodley** [comment]
Theory for what could be going wrong: the column data type of the custom tags dictionaries seem to be being converted back in the code from text to categorical (both are internal Orange column data types).

**Comment by ThijsVroegh** [comment]
Hi @kodymoodley , I tried to reproduce the error above, but in my case it does seem to work correctly (i.e., I only get the words from the custom tag list). Do you think this error might be dependent on the system one has (which I doubt btw)?

**Comment by ThijsVroegh** [comment]
Hi @eriktks, could you perhaps also briefly check if you get the same results as Kody? It works fine on my computer, so I wanted to double check.

**Comment by ThijsVroegh** [comment]
@eriktks ; nevermind, I reproduced the error now..

**Comment by eriktks** [comment]
solved by PR #79
